### PR TITLE
TableData service is already cached

### PR DESCRIPTION
**Pull request by nightlyone**
see https://godoc.org/google.golang.org/api/bigquery/v2#Service

### CODE REVIEW

**Comment by avivl** [comment]
@oryband

**Comment by nightlyone** [comment]
test due to testing with unsupported Go versions. Fixed in #12

**Comment by oryband** [comment]
Hi @nightlyone 

Thanks for the PR. I'm currently working on a v2 branch for go-bqstreamer, and will release it soon. I've stopped all work on the current (v1) version, including accepting PRs. Please see [#7](https://github.com/rounds/go-bqstreamer/issues/7#issuecomment-195999300). 

However - I'll merge this into v2 once it's ready. Keeping this issue open until then.

> test due to testing with unsupported Go versions. Fixed in #12

I didn't quite understand what you were trying to say here. Did you mean the Travis build failed because of #12 ?

**Comment by nightlyone** [comment]
ok, great to know! Will closed it for now. I explained the Go version issue in #12

**Comment by oryband** [comment]
No, no, I want to keep it open so I won't forget to fix this on my own.

**Comment by oryband** [comment]
hi @nightlyone , #16 has just been merged. can you please update your pr?

thanks and sorry for keeping you waiting for so long

**Comment by nightlyone** [comment]
@oryband anything missing that blocks a merge?

**Comment by nightlyone** [comment]
@oryband anything I can do to help?

**Comment by nightlyone** [comment]
Gentle ping. @oryband

**Comment by oryband** [comment]
@nightlyone I'm no longer maintaining this repository. Thank you very much for the contribution. Feel free to fork and continue development.

**Comment by nightlyone** [comment]
No longer maintained and I don't use it anymore. So closed.

**Pull request closed without merging**
