### PR TITLE
Added a Func in MutliStreamer to get queue length 

### PR DESCRIPTION
**Pull request by eranchetz**
Basically it's the sum of indexes of all single streamers of a multi streamer

### CODE REVIEW

**Comment by avivl** [comment]
@oryband

**Comment by oryband** [comment]
Hi @eranchetz , and thanks for the PR!

That's a good idea, and I'll happily merge this soon. I'm currently working on a v2 branch for go-bqstreamer, and have stopped all work on the current (v1) version, including accepting PR. Please see [#7](https://github.com/rounds/go-bqstreamer/issues/7#issuecomment-195999300)

However - I'll merge this into v2 once it's ready. Keeping this issue open until then.

**Comment by eranchetz** [comment]
Thanks a lot for the update. can't wait for the new version.

**Comment by oryband** [comment]
@eranchetz me too.

**Comment by dotwaffle** [comment]
Could you implement this for single streamer too? At present I have no idea whether entries are backing up or not, it would be useful to know!

**Comment by eranchetz** [comment]
@dotwaffle I would love to implement this as well but currently it seems the project is in code freeze.
@oryband is that true?

**Comment by oryband** [comment]
> @dotwaffle I would love to implement this as well but currently it seems the project is in code freeze.
> @oryband is that true?

Since v2 will have breaking changes, no point in adding code to the current v1 version.

> Could you implement this for single streamer too? At present I have no idea whether entries are backing up or not, it would be useful to know!

This is somewhat related to #8 . I'll make sure to add it in v2.

-------
Sorry for making you wait guys, I have other priorities as well, but will get to this soon.

**Comment by oryband** [comment]
hi @eranchetz , #16 has been merged. please update this pr (with tests) and i'll merge it.

thanks and sorry for keeping you waiting for so long!

**Comment by oryband** [comment]
@eranchetz i thought about this - and it is a bit "dangerous" to count internal members for background executing goroutines (workers). While counting the internal `rows` member for each background worker, the workers can insert to bigquery and "flush" their row slice back to size 0. In order to make this function count properly, we need to implement locking. What do you think?

In any case I've just implemented this for `SyncWorker` in #15, since there's asynchronous in the way it works.

**Comment by eranchetz** [comment]
@oryband @dotwaffle I am closing this pull request, and will create a new one 👍

**Comment by oryband** [comment]
@eranchetz thx! :+1:

**Pull request closed without merging**
